In [1]:
# ============================================
# ABTalks Season-3 AI Engineering - Task Day 19
# Focus Area: Numerical Stability
# Tool/Tech: NumPy
# Problem Statement:
# Normalize embedding vectors and analyze impact
# ============================================

import numpy as np

# For clean output
np.set_printoptions(precision=4, suppress=True)

print("=" * 70)
print("DAY 19 TASK - NUMERICAL STABILITY WITH EMBEDDING NORMALIZATION")
print("=" * 70)


# ------------------------------------------------
# STEP 1: Create Sample Embedding Vectors
# ------------------------------------------------
print("\n1. Creating sample embedding vectors...")

embedding_vectors = np.array([
    [120.5, 340.2, 560.1, 220.7, 150.3],
    [12.1, 34.8, 56.4, 22.9, 15.7],
    [950.2, 1200.6, 870.5, 660.4, 430.8],
    [0.001, 0.002, 0.003, 0.004, 0.005]   # Edge case: very small values
])

print("Original Embedding Vectors:\n")
print(embedding_vectors)


# ------------------------------------------------
# STEP 2: Define Numerically Stable Normalization
# ------------------------------------------------
print("\n2. Applying numerically stable vector normalization...")

def normalize_vectors(vectors, epsilon=1e-10):
    """
    Normalize vectors safely using L2 normalization.
    epsilon prevents division by zero.
    """
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    normalized = vectors / (norms + epsilon)
    return normalized, norms

normalized_vectors, vector_norms = normalize_vectors(embedding_vectors)

print("\nVector Norms:")
print(vector_norms)

print("\nNormalized Embedding Vectors:")
print(normalized_vectors)


# ------------------------------------------------
# STEP 3: Cosine Similarity Function
# ------------------------------------------------
print("\n3. Computing cosine similarity...")

def cosine_similarity(vec1, vec2):
    """
    Compute cosine similarity safely.
    """
    dot_product = np.dot(vec1, vec2)
    norm_product = (np.linalg.norm(vec1) * np.linalg.norm(vec2)) + 1e-10
    return dot_product / norm_product


# ------------------------------------------------
# STEP 4: Similarity BEFORE normalization
# ------------------------------------------------
print("\n4. Similarity BEFORE normalization")

before_similarity_1 = cosine_similarity(
    embedding_vectors[0],
    embedding_vectors[1]
)

before_similarity_2 = cosine_similarity(
    embedding_vectors[0],
    embedding_vectors[2]
)

print(f"Similarity (Vector 1 vs Vector 2): {before_similarity_1:.6f}")
print(f"Similarity (Vector 1 vs Vector 3): {before_similarity_2:.6f}")


# ------------------------------------------------
# STEP 5: Similarity AFTER normalization
# ------------------------------------------------
print("\n5. Similarity AFTER normalization")

after_similarity_1 = cosine_similarity(
    normalized_vectors[0],
    normalized_vectors[1]
)

after_similarity_2 = cosine_similarity(
    normalized_vectors[0],
    normalized_vectors[2]
)

print(f"Similarity (Vector 1 vs Vector 2): {after_similarity_1:.6f}")
print(f"Similarity (Vector 1 vs Vector 3): {after_similarity_2:.6f}")


# ------------------------------------------------
# STEP 6: Analyze scaling impact
# ------------------------------------------------
print("\n6. Analyzing scaling impact...")

scaled_vector = embedding_vectors[0] * 10000

similarity_scaled_before = cosine_similarity(
    embedding_vectors[0],
    scaled_vector
)

normalized_original, _ = normalize_vectors(
    np.array([embedding_vectors[0]])
)

normalized_scaled, _ = normalize_vectors(
    np.array([scaled_vector])
)

similarity_scaled_after = cosine_similarity(
    normalized_original[0],
    normalized_scaled[0]
)

print(f"Similarity with scaled vector BEFORE normalization: {similarity_scaled_before:.6f}")
print(f"Similarity with scaled vector AFTER normalization:  {similarity_scaled_after:.6f}")


# ------------------------------------------------
# STEP 7: Numerical Stability Edge Case
# ------------------------------------------------
print("\n7. Testing numerical stability with near-zero vectors...")

near_zero_vector = np.array([[0.0, 0.0, 0.0, 0.0, 0.0]])

stable_normalized, stable_norm = normalize_vectors(near_zero_vector)

print("Near-zero vector norm:")
print(stable_norm)

print("Safely normalized near-zero vector:")
print(stable_normalized)


# ------------------------------------------------
# STEP 8: Final Analysis
# ------------------------------------------------
print("\n8. Final Analysis")

print("""
Key Observations:
1. Raw embeddings can have vastly different magnitudes.
2. Normalization converts vectors to unit length.
3. Cosine similarity becomes more reliable after normalization.
4. Scaling large vectors does not affect normalized similarity.
5. epsilon prevents division-by-zero errors.
6. This improves numerical stability in NLP and ML pipelines.
""")


print("=" * 70)
print("TASK COMPLETED SUCCESSFULLY")
print("=" * 70)

DAY 19 TASK - NUMERICAL STABILITY WITH EMBEDDING NORMALIZATION

1. Creating sample embedding vectors...
Original Embedding Vectors:

[[ 120.5    340.2    560.1    220.7    150.3  ]
 [  12.1     34.8     56.4     22.9     15.7  ]
 [ 950.2   1200.6    870.5    660.4    430.8  ]
 [   0.001    0.002    0.003    0.004    0.005]]

2. Applying numerically stable vector normalization...

Vector Norms:
[[ 717.8209]
 [  72.865 ]
 [1929.7169]
 [   0.0074]]

Normalized Embedding Vectors:
[[0.1679 0.4739 0.7803 0.3075 0.2094]
 [0.1661 0.4776 0.774  0.3143 0.2155]
 [0.4924 0.6222 0.4511 0.3422 0.2232]
 [0.1348 0.2697 0.4045 0.5394 0.6742]]

3. Computing cosine similarity...

4. Similarity BEFORE normalization
Similarity (Vector 1 vs Vector 2): 0.999930
Similarity (Vector 1 vs Vector 3): 0.881474

5. Similarity AFTER normalization
Similarity (Vector 1 vs Vector 2): 0.999930
Similarity (Vector 1 vs Vector 3): 0.881474

6. Analyzing scaling impact...
Similarity with scaled vector BEFORE normalization: 

In [2]:
# ==========================================================
# ABTalks Season-3 AI Engineering | Task Day 19
# Focus Area: Numerical Stability
# Tool/Tech: NumPy
# Problem Statement:
# Normalize embedding vectors and analyze impact
# ==========================================================

import numpy as np

np.set_printoptions(precision=4, suppress=True)

print("=" * 80)
print("DAY 19 TASK - NUMERICAL STABILITY & EMBEDDING NORMALIZATION")
print("=" * 80)

# ----------------------------------------------------------
# 1. Create Sample Embedding Vectors
# ----------------------------------------------------------
print("\n1. Creating sample embedding vectors...")

embeddings = np.array([
    [120.5, 340.2, 560.1, 220.7, 150.3],
    [15.2, 42.8, 68.1, 27.4, 18.9],
    [980.3, 1250.7, 890.4, 670.2, 450.9],
    [0.001, 0.002, 0.003, 0.004, 0.005]  # Very small values
])

print("\nOriginal Embeddings:")
print(embeddings)


# ----------------------------------------------------------
# 2. Numerically Stable Normalization Function
# ----------------------------------------------------------
def normalize_embeddings(vectors, epsilon=1e-12):
    """
    Perform numerically stable L2 normalization.
    epsilon prevents division by zero.
    """
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    normalized = vectors / np.maximum(norms, epsilon)
    return normalized, norms


print("\n2. Applying numerically stable normalization...")

normalized_embeddings, norms = normalize_embeddings(embeddings)

print("\nVector Norms:")
print(norms)

print("\nNormalized Embeddings:")
print(normalized_embeddings)


# ----------------------------------------------------------
# 3. Similarity Functions
# ----------------------------------------------------------
def dot_product_similarity(vec1, vec2):
    return np.dot(vec1, vec2)


def cosine_similarity(vec1, vec2, epsilon=1e-12):
    norm_product = (np.linalg.norm(vec1) * np.linalg.norm(vec2))
    return np.dot(vec1, vec2) / max(norm_product, epsilon)


# ----------------------------------------------------------
# 4. Similarity BEFORE Normalization
# ----------------------------------------------------------
print("\n3. Similarity BEFORE normalization")

raw_dot_1 = dot_product_similarity(embeddings[0], embeddings[1])
raw_dot_2 = dot_product_similarity(embeddings[0], embeddings[2])

raw_cos_1 = cosine_similarity(embeddings[0], embeddings[1])
raw_cos_2 = cosine_similarity(embeddings[0], embeddings[2])

print(f"\nRaw Dot Product (Vector1 vs Vector2): {raw_dot_1:.4f}")
print(f"Raw Dot Product (Vector1 vs Vector3): {raw_dot_2:.4f}")

print(f"Raw Cosine Similarity (Vector1 vs Vector2): {raw_cos_1:.6f}")
print(f"Raw Cosine Similarity (Vector1 vs Vector3): {raw_cos_2:.6f}")


# ----------------------------------------------------------
# 5. Similarity AFTER Normalization
# ----------------------------------------------------------
print("\n4. Similarity AFTER normalization")

norm_dot_1 = dot_product_similarity(normalized_embeddings[0], normalized_embeddings[1])
norm_dot_2 = dot_product_similarity(normalized_embeddings[0], normalized_embeddings[2])

norm_cos_1 = cosine_similarity(normalized_embeddings[0], normalized_embeddings[1])
norm_cos_2 = cosine_similarity(normalized_embeddings[0], normalized_embeddings[2])

print(f"\nNormalized Dot Product (Vector1 vs Vector2): {norm_dot_1:.6f}")
print(f"Normalized Dot Product (Vector1 vs Vector3): {norm_dot_2:.6f}")

print(f"Normalized Cosine Similarity (Vector1 vs Vector2): {norm_cos_1:.6f}")
print(f"Normalized Cosine Similarity (Vector1 vs Vector3): {norm_cos_2:.6f}")


# ----------------------------------------------------------
# 6. Analyze Scaling Impact
# ----------------------------------------------------------
print("\n5. Analyzing impact of scaling...")

scaled_vector = embeddings[0] * 10000

scaled_dot = dot_product_similarity(embeddings[0], scaled_vector)
scaled_cos = cosine_similarity(embeddings[0], scaled_vector)

scaled_norm, _ = normalize_embeddings(np.array([scaled_vector]))
orig_norm, _ = normalize_embeddings(np.array([embeddings[0]]))

scaled_norm_dot = dot_product_similarity(orig_norm[0], scaled_norm[0])
scaled_norm_cos = cosine_similarity(orig_norm[0], scaled_norm[0])

print(f"\nDot Product BEFORE normalization with scaled vector: {scaled_dot:.4f}")
print(f"Cosine Similarity BEFORE normalization with scaled vector: {scaled_cos:.6f}")

print(f"Dot Product AFTER normalization with scaled vector: {scaled_norm_dot:.6f}")
print(f"Cosine Similarity AFTER normalization with scaled vector: {scaled_norm_cos:.6f}")


# ----------------------------------------------------------
# 7. Numerical Stability Edge Case
# ----------------------------------------------------------
print("\n6. Testing zero-vector numerical stability...")

zero_vector = np.array([[0.0, 0.0, 0.0, 0.0, 0.0]])

safe_zero_norm, zero_norm_value = normalize_embeddings(zero_vector)

print("\nZero Vector Norm:")
print(zero_norm_value)

print("\nSafely Normalized Zero Vector:")
print(safe_zero_norm)


# ----------------------------------------------------------
# 8. Final Analysis
# ----------------------------------------------------------
print("\n7. Analysis & Insights")

print("""
KEY INSIGHTS:

1. Raw embedding vectors have different magnitudes.
   This can distort similarity calculations.

2. L2 normalization converts vectors to unit length.
   This makes comparisons fair and stable.

3. Dot product similarity changes drastically due to scale.
   This proves normalization importance.

4. Cosine similarity focuses on direction rather than magnitude.

5. Scaling vectors can break raw similarity measures,
   but normalized vectors remain stable.

6. epsilon/max() prevents division-by-zero issues.

7. This is critical in NLP embeddings, recommendation systems,
   semantic search, and machine learning pipelines.
""")

print("=" * 80)
print("TASK DAY 19 COMPLETED SUCCESSFULLY")
print("=" * 80)

DAY 19 TASK - NUMERICAL STABILITY & EMBEDDING NORMALIZATION

1. Creating sample embedding vectors...

Original Embeddings:
[[ 120.5    340.2    560.1    220.7    150.3  ]
 [  15.2     42.8     68.1     27.4     18.9  ]
 [ 980.3   1250.7    890.4    670.2    450.9  ]
 [   0.001    0.002    0.003    0.004    0.005]]

2. Applying numerically stable normalization...

Vector Norms:
[[ 717.8209]
 [  88.3655]
 [1992.6188]
 [   0.0074]]

Normalized Embeddings:
[[0.1679 0.4739 0.7803 0.3075 0.2094]
 [0.172  0.4844 0.7707 0.3101 0.2139]
 [0.492  0.6277 0.4468 0.3363 0.2263]
 [0.1348 0.2697 0.4045 0.5394 0.6742]]

3. Similarity BEFORE normalization

Raw Dot Product (Vector1 vs Vector2): 63422.8200
Raw Dot Product (Vector1 vs Vector3): 1258010.7400
Raw Cosine Similarity (Vector1 vs Vector2): 0.999877
Raw Cosine Similarity (Vector1 vs Vector3): 0.879517

4. Similarity AFTER normalization

Normalized Dot Product (Vector1 vs Vector2): 0.999877
Normalized Dot Product (Vector1 vs Vector3): 0.879517
Nor